[project]
name = "XeF4"
version = "1.0.0"
description = "A multifunctional QQ group robot"
readme = "README.md"
requires-python = ">=3.9, <4.0"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "ddgs>=9.5.4",
    "langchain>=0.3.27",
    "langchain-community>=0.3.27",
    "langchain-openai>=0.3.31",
    "matplotlib>=3.9.4",
    "mcstatus>=12.0.5",
    "nonebot-adapter-minecraft>=1.4.2",
    "nonebot-adapter-onebot>=2.4.6",
    "nonebot-plugin-alconna>=0.59.4",
    "nonebot-plugin-apscheduler>=0.5.0",
    "nonebot-plugin-localstore>=0.7.4",
    "nonebot2[fastapi,websockets]>=2.4.3",
]

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
    { name = "Minecraft", module_name = "nonebot.adapters.minecraft" }
]
plugins = ["nonebot_plugin_alconna", "nonebot_plugin_apscheduler", "nonebot_plugin_localstore"]
plugin_dirs = ["src/plugins"]
builtin_plugins = []

[tool.ruff]
ignore = ["E402"]
